name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read the right version of Go
        id: golang_version
        run: |
          golangVersion=$(grep '^golang ' .tool-versions | awk '{print $2}')
          echo "golangVersion=${golangVersion}" >> $GITHUB_OUTPUT

      - uses: cli/gh-extension-precompile@v1
        with:
          go_version: ${{ steps.golang_version.outputs.golangVersion }}
